# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: continuumio/miniconda3:latest

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Install requirements.
        caches:
          - conda
          - pip
        script: # Modify the commands below to build your repository.
          - conda env update -n solvers --file env_solvers.yml
    - parallel:
        - step: # Run tests
            name: Run tests and codecoverage.
            caches:
                - conda
                - pip
            script:
                - conda env update -n solvers --file env_solvers.yml
                - conda activate solvers
                #- pytest --cov=solvers ./tests --cov-report html:test-reports/code_coverage
                - pytest -v --cov=solvers ./tests --cov-report html:test-reports/coverage tests -m "not workinprogress"
                - apt-get update && apt-get --yes install zip
                - zip -r test-reports/coverage.zip test-reports/coverage
                - pipe: atlassian/bitbucket-upload-file:0.3.1
                  variables:
                      BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                      BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                      FILENAME: "test-reports/coverage.zip"

definitions:
   caches:
     conda: ~/.conda/envs/solvers
     codatarballs: /opt/conda/pkgs